name: .NET

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  pull_request:
    branches: [ main ]

  release:
    types: [ published ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # Failure

    - name: Restore Failure
      run: dotnet restore ./src/*/*/Failure.csproj

    - name: Build Failure
      run: dotnet build ./src/*/*/Failure.csproj --no-restore  -c Release

    - name: Pack Failure
      run: dotnet pack ./src/*/*/Failure.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Failure.Tests
      run: dotnet restore ./src/*/*/Failure.Tests.csproj

    - name: Test Failure.Tests
      run: dotnet test ./src/*/*/Failure.Tests.csproj --no-restore  -c Release

    # Optional

    - name: Restore Optional
      run: dotnet restore ./src/*/*/Optional.csproj

    - name: Build Optional
      run: dotnet build ./src/*/*/Optional.csproj --no-restore  -c Release

    - name: Pack Optional
      run: dotnet pack ./src/*/*/Optional.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Optional.Tests.Old
      run: dotnet restore ./src/*/*/Optional.Tests.Old.csproj

    - name: Test Optional.Tests.Old
      run: dotnet test ./src/*/*/Optional.Tests.Old.csproj --no-restore  -c Release

    - name: Restore Optional.Tests
      run: dotnet restore ./src/*/*/Optional.Tests.csproj

    - name: Test Optional.Tests
      run: dotnet test ./src/*/*/Optional.Tests.csproj --no-restore  -c Release

    # Result

    - name: Restore Result
      run: dotnet restore ./src/*/*/Result.csproj

    - name: Build Result
      run: dotnet build ./src/*/*/Result.csproj --no-restore  -c Release

    - name: Pack Result
      run: dotnet pack ./src/*/*/Result.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Result.Tests.Old
      run: dotnet restore ./src/*/*/Result.Tests.Old.csproj

    - name: Test Result.Tests.Old
      run: dotnet test ./src/*/*/Result.Tests.Old.csproj --no-restore  -c Release

    - name: Restore Result.Tests
      run: dotnet restore ./src/*/*/Result.Tests.csproj

    - name: Test Result.Tests
      run: dotnet test ./src/*/*/Result.Tests.csproj --no-restore  -c Release

    # Taggeds

    - name: Restore Taggeds
      run: dotnet restore ./src/*/*/Taggeds.csproj

    - name: Build Taggeds
      run: dotnet build ./src/*/*/Taggeds.csproj --no-restore  -c Release

    - name: Pack Taggeds
      run: dotnet pack ./src/*/*/Taggeds.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Taggeds.Tests.Old
      run: dotnet restore ./src/*/*/Taggeds.Tests.Old.csproj

    - name: Test Taggeds.Tests.Old
      run: dotnet test ./src/*/*/Taggeds.Tests.Old.csproj --no-restore  -c Release

    - name: Restore Taggeds.Tests
      run: dotnet restore ./src/*/*/Taggeds.Tests.csproj

    - name: Test Taggeds.Tests
      run: dotnet test ./src/*/*/Taggeds.Tests.csproj --no-restore  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
