name: .NET

on:
  push:
    branches: [ master, dev, dev/*, feature/*, fix/*, release/* ]

  pull_request:
    branches: [ master ]

  release:
    types: [ published ]
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

      # Unit

    - name: Restore Unit
      run: dotnet restore ./src/*/*/Unit.csproj

    - name: Build Unit
      run: dotnet build ./src/*/*/Unit.csproj --no-restore  -c Release

    - name: Pack Unit
      run: dotnet pack ./src/*/*/Unit.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Unit.Tests
      run: dotnet restore ./src/*/*/Unit.Tests.csproj

    - name: Test Unit.Tests
      run: dotnet test ./src/*/*/Unit.Tests.csproj --no-restore  -c Release

    # Func.Abstractions.Async

    - name: Restore Func.Abstractions.Async
      run: dotnet restore ./src/*/*/Func.Abstractions.Async.csproj

    - name: Build Func.Abstractions.Async
      run: dotnet build ./src/*/*/Func.Abstractions.Async.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.Async
      run: dotnet pack ./src/*/*/Func.Abstractions.Async.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions.AsyncValue

    - name: Restore Func.Abstractions.AsyncValue
      run: dotnet restore ./src/*/*/Func.Abstractions.AsyncValue.csproj

    - name: Build Func.Abstractions.AsyncValue
      run: dotnet build ./src/*/*/Func.Abstractions.AsyncValue.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.AsyncValue
      run: dotnet pack ./src/*/*/Func.Abstractions.AsyncValue.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions.Sync

    - name: Restore Func.Abstractions.Sync
      run: dotnet restore ./src/*/*/Func.Abstractions.Sync.csproj

    - name: Build Func.Abstractions.Sync
      run: dotnet build ./src/*/*/Func.Abstractions.Sync.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.Sync
      run: dotnet pack ./src/*/*/Func.Abstractions.Sync.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions

    - name: Restore Func.Abstractions
      run: dotnet restore ./src/*/*/Func.Abstractions.csproj

    - name: Build Func.Abstractions
      run: dotnet build ./src/*/*/Func.Abstractions.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions
      run: dotnet pack ./src/*/*/Func.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    # Func.Extensions.Async

    - name: Restore Func.Extensions.Async
      run: dotnet restore ./src/*/*/Func.Extensions.Async.csproj

    - name: Build Func.Extensions.Async
      run: dotnet build ./src/*/*/Func.Extensions.Async.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.Async
      run: dotnet pack ./src/*/*/Func.Extensions.Async.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.Async.Tests
      run: dotnet restore ./src/*/*/Func.Extensions.Async.Tests.csproj

    - name: Test Func.Extensions.Async.Tests
      run: dotnet test ./src/*/*/Func.Extensions.Async.Tests.csproj --no-restore  -c Release

    # Func.Extensions.AsyncValue

    - name: Restore Func.Extensions.AsyncValue
      run: dotnet restore ./src/*/*/Func.Extensions.AsyncValue.csproj

    - name: Build Func.Extensions.AsyncValue
      run: dotnet build ./src/*/*/Func.Extensions.AsyncValue.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.AsyncValue
      run: dotnet pack ./src/*/*/Func.Extensions.AsyncValue.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.AsyncValue.Tests
      run: dotnet restore ./src/*/*/Func.Extensions.AsyncValue.Tests.csproj

    - name: Test Func.Extensions.AsyncValue.Tests
      run: dotnet test ./src/*/*/Func.Extensions.AsyncValue.Tests.csproj --no-restore  -c Release

    # Func.Extensions.Sync

    - name: Restore Func.Extensions.Sync
      run: dotnet restore ./src/*/*/Func.Extensions.Sync.csproj

    - name: Build Func.Extensions.Sync
      run: dotnet build ./src/*/*/Func.Extensions.Sync.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.Sync
      run: dotnet pack ./src/*/*/Func.Extensions.Sync.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.Sync.Tests
      run: dotnet restore ./src/*/*/Func.Extensions.Sync.Tests.csproj

    - name: Test Func.Extensions.Sync.Tests
      run: dotnet test ./src/*/*/Func.Extensions.Sync.Tests.csproj --no-restore  -c Release

    # Func.Extensions

    - name: Restore Func.Extensions
      run: dotnet restore ./src/*/*/Func.Extensions.csproj

    - name: Build Func.Extensions
      run: dotnet build ./src/*/*/Func.Extensions.csproj --no-restore  -c Release

    - name: Pack Func.Extensions
      run: dotnet pack ./src/*/*/Func.Extensions.csproj --no-restore -o ~/nuget  -c Release

    # Failure

    - name: Restore Failure
      run: dotnet restore ./src/*/*/Failure.csproj

    - name: Build Failure
      run: dotnet build ./src/*/*/Failure.csproj --no-restore  -c Release

    - name: Pack Failure
      run: dotnet pack ./src/*/*/Failure.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Failure.Tests
      run: dotnet restore ./src/*/*/Failure.Tests.csproj

    - name: Test Failure.Tests
      run: dotnet test ./src/*/*/Failure.Tests.csproj --no-restore  -c Release

    # Optional

    - name: Restore Optional
      run: dotnet restore ./src/*/*/Optional.csproj

    - name: Build Optional
      run: dotnet build ./src/*/*/Optional.csproj --no-restore  -c Release

    - name: Pack Optional
      run: dotnet pack ./src/*/*/Optional.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Optional.Tests
      run: dotnet restore ./src/*/*/Optional.Tests.csproj

    - name: Test Optional.Tests
      run: dotnet test ./src/*/*/Optional.Tests.csproj --no-restore  -c Release

    # TaggedUnion

    - name: Restore TaggedUnion
      run: dotnet restore ./src/*/*/TaggedUnion.csproj

    - name: Build TaggedUnion
      run: dotnet build ./src/*/*/TaggedUnion.csproj --no-restore  -c Release

    - name: Pack TaggedUnion
      run: dotnet pack ./src/*/*/TaggedUnion.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore TaggedUnion.Tests
      run: dotnet restore ./src/*/*/TaggedUnion.Tests.csproj

    - name: Test TaggedUnion.Tests
      run: dotnet test ./src/*/*/TaggedUnion.Tests.csproj --no-restore  -c Release

    # Result

    - name: Restore Result
      run: dotnet restore ./src/*/*/Result.csproj

    - name: Build Result
      run: dotnet build ./src/*/*/Result.csproj --no-restore  -c Release

    - name: Pack Result
      run: dotnet pack ./src/*/*/Result.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Result.Tests
      run: dotnet restore ./src/*/*/Result.Tests.csproj

    - name: Test Result.Tests
      run: dotnet test ./src/*/*/Result.Tests.csproj --no-restore  -c Release

    # Taggeds

    - name: Restore Taggeds
      run: dotnet restore ./src/*/*/Taggeds.csproj

    - name: Build Taggeds
      run: dotnet build ./src/*/*/Taggeds.csproj --no-restore  -c Release

    - name: Pack Taggeds
      run: dotnet pack ./src/*/*/Taggeds.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Taggeds.Tests
      run: dotnet restore ./src/*/*/Taggeds.Tests.csproj

    - name: Test Taggeds.Tests
      run: dotnet test ./src/*/*/Taggeds.Tests.csproj --no-restore  -c Release

    # Core

    - name: Restore Core
      run: dotnet restore ./src/*/*/Core.csproj

    - name: Build Core
      run: dotnet build ./src/*/*/Core.csproj --no-restore  -c Release

    - name: Pack Core
      run: dotnet pack ./src/*/*/Core.csproj --no-restore -o ~/nuget  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetSourcePassword }} --skip-duplicate
